apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicated-web
spec:
  replicas: 5
  selector:
    matchLabels:
      replicaset: replicated-web
  template:
    metadata:
      labels:
        replicaset: replicated-web
    spec:
	  nodeSelector:
	    type: main
      containers:
      - name: web
        image: nginx