apiVersion: v1
kind: Pod
metadata:
  name: nginx-vol
spec:
  containers:
  - image: nginx
    name: nginx-host
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-host-volume
  volumes:
  - name: nginx-host-volume
    hostPath:
      # directory location on host
      path: "/tmp/www"
      # this field is optional
      type: DirectoryOrCreate
  nodeSelector:
    hostpath: configured
