apiVersion: v1
kind: Pod
metadata:
  name: nginx-vol3
spec:
  containers:
  - image: nginx
    name: nginx-host
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-host-volume
  volumes:
    - name: nginx-host-volume
      persistentVolumeClaim:
        claimName: pvc01
  nodeSelector:
    hostpath: configured
