apiVersion: v1
kind: Pod
metadata:
  name: nginx-01
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nfs-vol
  volumes:
  - name: nfs-vol
    nfs:
      server: 10.1.121.28
      path: /volume1/NFS_K8S