apiVersion: v1
kind: Pod
metadata:
  name: nginx-vol-secondary
  labels:
    app: webserver-01
spec:
  containers:
  - image: nginx
    name: nginx-host
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-nfs-volume
  volumes:
    - name: nginx-nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc01
