apiVersion: apps/v1
kind: Deployment
metadata:
  name: pws
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pws
  template:
    metadata:
      labels:
        app: pws
    spec:
      containers:
      - name: pws
        image: bogd/python-webserver

---
kind: Service
apiVersion: v1
metadata:
  name: pws
spec:
  selector:
    app: pws
  ports:
  - protocol: TCP
    port: 8081