apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
spec:
  storageClassName: nfs
  capacity:
    storage: 50G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.1.121.28
    path: "/volume1/NFS_K8S"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-demo
spec:
  storageClassName: nfs
#  volumeName: pv-demo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50G